### PR TITLE
 Convert questions to a string, fixes #243

### LINKED ISSUE #243: Fails when composer uses `symfony/console:^4`
See composer/composer#7199

`z-e-s` calls [ConsoleIO::ask() with array argument](https://github.com/zendframework/zend-expressive-skeleton/blob/a50879bfeedcd563596e61eb08e62238467187dc/src/ExpressiveInstaller/OptionalPackages.php#L254), and that fails when composer uses `symfony/console:^4`

Steps to reproduce:
1. install composer as a global composer package
2. configure your $PATH to run that
3. update global `symfony/console` to ^4
3. run `composer create-project zendframework/zend-expressive-skeleton dir`

Expected:
No failures, installer asks what router/templater/di container to use

Actual:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given, called in /home/weirdan/.compose
r/vendor/composer/composer/src/Composer/IO/ConsoleIO.php on line 239 and defined in /home/weirdan/.composer/vendor/symfony/console/Question/Question.php:37
Stack trace:
#0 /home/weirdan/.composer/vendor/composer/composer/src/Composer/IO/ConsoleIO.php(239): Symfony\Component\Console\Question\Question->__construct(Array, '2')
#1 /home/weirdan/src/t/src/ExpressiveInstaller/OptionalPackages.php(254): Composer\IO\ConsoleIO->ask(Array, '2')
#2 /home/weirdan/src/t/src/ExpressiveInstaller/OptionalPackages.php(175): ExpressiveInstaller\OptionalPackages->requestInstallType()
#3 /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): ExpressiveInstaller\OptionalPackages::install(Object(Composer\Script\Event))
#4 /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatche in /home/weirdan/.composer/vendor/symfony/console/Question/Question.php on line 37

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given, called in /home/weirdan/.composer/vendor/composer/composer/src/Composer/IO/ConsoleIO.php on line 239 and defined in /home/weirdan/.composer/vendor/symfony/console/Question/Question.php:37
Stack trace:
#0 /home/weirdan/.composer/vendor/composer/composer/src/Composer/IO/ConsoleIO.php(239): Symfony\Component\Console\Question\Question->__construct(Array, '2')
#1 /home/weirdan/src/t/src/ExpressiveInstaller/OptionalPackages.php(254): Composer\IO\ConsoleIO->ask(Array, '2')
#2 /home/weirdan/src/t/src/ExpressiveInstaller/OptionalPackages.php(175): ExpressiveInstaller\OptionalPackages->requestInstallType()
#3 /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): ExpressiveInstaller\OptionalPackages::install(Object(Composer\Script\Event))
#4 /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatche in /home/weirdan/.composer/vendor/symfony/console/Question/Question.php on line 37
```

**Edit**: Current `composer.phar` that can be downloaded from getcomposer.org does not suffer from this issue. Apparently it uses older `symfony/console` package.

### PR DESCRIPTION
**Pull request by xtreamwayz**
Since symfony/console 4 questions only accept a question string. Looking at its history, this was always the case and is wrong in the composer docblock.

see: https://github.com/symfony/console/blob/4.0/Question/Question.php#L37
see: https://github.com/composer/composer/blob/1.6/src/Composer/IO/IOInterface.php#L106

### CODE REVIEW

File: test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php [hunk 1]
```diff
@@ -90,8 +90,16 @@ public function testPromptForOptionalPackage(
...
-        $argument = is_array($argument) ? array_shift($argument) : $argument;
-        $message = sprintf('Expected prompt not received: "%s"', $expected);
-        self::assertThat(false !== strpos($argument, $expected), self::isTrue(), $message);
+        self::assertInternalType(
+            'string',
+            $argument,
+            'Questions must be a string since symfony/console:4.0'
+        );
+
+        self::assertThat(
```
Comment (webimpress) [inline test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php]: Why not `assertTrue`?

**Comment by xtreamwayz** [comment]
> It's wrong milestone, should be 3.0.2.
> 3.0.1 is already released.

I just noticed when creating a new project :)

File: test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php (hunk 1 above)
Comment (xtreamwayz) [reply test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php]: Good question.

@mwop any reason you wrote it like this?

Comment (webimpress) [reply test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php]: I think you want to ask @weierophinney  ;-)

Comment (xtreamwayz) [reply test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php]: Works for me :)

Comment (weierophinney) [reply test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php]: Honestly, because it's how custom assertions are demonstrated in the manual: https://phpunit.de/manual/current/en/extending-phpunit.html

I'm fine with either approach.

Comment (webimpress) [reply test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php]: Hm... in the docs is just example, maybe a bit unfortunate, because `assertTrue` is one of the available assertions.

**Comment by xtreamwayz** [comment]
> Looks good, and I think we may need to do similar in the zend-component-installer.

Working on it.

**Comment by weierophinney** [comment]
Thanks, @xtreamwayz!
